name: Build

on: [workflow_dispatch]

env:
  # CMake build directory:
  build: '${{ github.workspace }}/build'
  build_type: 'Release'


jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install prerequisites
        run: sudo apt-get install -y ninja-build

      - name: print versions
        run: |
          ninja --version
          cmake --version

      - name: compile
        run: |
          cmake --version
          cmake . -GNinja -B ${{ env.build }} -DCMAKE_BUILD_TYPE=${{env.build_type}} -DSATSUMA_ENABLE_BLOSSOM5=0 -DCMAKE_EXE_LINKER_FLAGS="-static" -DBLA_STATIC=1 -D CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
          cmake --build ${{env.build}}

      - name: collect release
        run: |
          cmake -E make_directory release
          cmake -E copy ${{env.build}}/Build/lib/liblib_quadwild.so release
          cmake -E copy ${{env.build}}/Build/lib/liblib_quadpatches.so release
          cmake -E copy_directory config release/config
          cmake -E copy README_release.md release

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: linux-binaries
          path: |
            release/*


  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: compile
        run: |
          cmake --version
          cmake . -B ${{ env.build }} -T "ClangCl"  -DSATSUMA_ENABLE_BLOSSOM5=0 -D CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON
          cmake --build build --config ${{env.build_type}}

      - name: collect release
        run: |
          cmake -E make_directory release
          cmake -E copy_directory build\Build\bin\${{env.build_type}} release
          cmake -E copy_directory config release\config
          cmake -E copy README_release.md release

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: windows-binaries
          path: |
            release/*

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: install prerequisites
        run: brew install ninja

      - name: compile
        run: |
          cmake --version
          cmake . -GNinja -B ${{ env.build }} -DCMAKE_BUILD_TYPE=${{env.build_type}}  -DSATSUMA_ENABLE_BLOSSOM5=0 -D CMAKE_INTERPROCEDURAL_OPTIMIZATION=ON -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"
          cmake --build ${{env.build}}

      - name: collect release
        run: |
          cmake -E make_directory release
          cmake -E copy ${{env.build}}/Build/lib/liblib_quadwild.dylib release
          cmake -E copy ${{env.build}}/Build/lib/liblib_quadpatches.dylib release
          cmake -E copy_directory config release/config
          cmake -E copy README_release.md release

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: macos-binaries
          path: |
            release/*
